spring.application.name=similar-products
server.port=5000

# Products API URL (mocks)
product.api.base-url=http://localhost:3001

# Timeout (seconds) to get the details of each product.
# Products with delay greater than this value are omitted from the response.
product.api.detail-timeout-seconds=2